"""Human-readable and machine-readable renderings of a processed meeting.

Everything is rendered from the same ``RawTranscript``, ``RefinedTranscript``
and ``MeetingRecord`` objects, so the Markdown and JSON outputs always carry
the same decisions and action items. Owners and deadlines that were not stated
appear as "Unspecified" in Markdown and ``null`` in JSON.
"""

from __future__ import annotations

import csv
import io
import json
from dataclasses import dataclass

from ..schemas import UNSPECIFIED, MeetingRecord, RawTranscript, RefinedTranscript, Segment


@dataclass(frozen=True)
class ExportFile:
    key: str
    filename: str
    mime: str
    data: bytes


def timestamp(seconds: float) -> str:
    total = int(seconds)
    return f"{total // 3600:02d}:{total % 3600 // 60:02d}:{total % 60:02d}"


def transcript_text(segments: list[Segment]) -> str:
    return "\n".join(
        f"[{timestamp(s.start)} - {timestamp(s.end)}] (#{s.id}) {s.text.strip()}"
        for s in segments if s.text.strip()
    ) + "\n"


def _cite(ids: list[int], quote: str) -> str:
    return f'_Evidence (segment {", ".join(f"#{i}" for i in ids)}): "{quote}"_'


def _cell(text: str) -> str:
    """Make text safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


def record_markdown(record: MeetingRecord, title: str = "Meeting record") -> str:
    lines = [f"# {title}", ""]
    lines += ["## Summary", "", record.summary or "_Summary withheld: it failed validation._", ""]

    lines += ["## Minutes", ""]
    if record.minutes:
        for m in record.minutes:
            ids = ", ".join(f"#{i}" for i in m.segment_ids)
            lines += [f"### {m.topic}", "", m.discussion, "", f"_Segments: {ids}_", ""]
    else:
        lines += ["_No minutes._", ""]

    lines += ["## Decisions", ""]
    if record.decisions:
        for n, d in enumerate(record.decisions, 1):
            lines += [f"{n}. {d.decision}", f"   {_cite(d.evidence_segment_ids, d.evidence_quote)}"]
        lines.append("")
    else:
        lines += ["_No decisions were recorded._", ""]

    lines += ["## Proposals (discussed, not agreed)", ""]
    if record.proposals:
        for n, p in enumerate(record.proposals, 1):
            lines += [f"{n}. {p.proposal}", f"   {_cite(p.evidence_segment_ids, p.evidence_quote)}"]
        lines.append("")
    else:
        lines += ["_No open proposals._", ""]

    lines += ["## Action items", ""]
    if record.action_items:
        lines += ["| # | Task | Owner | Deadline | Evidence |", "|---|---|---|---|---|"]
        for n, a in enumerate(record.action_items, 1):
            ids = ", ".join(f"#{i}" for i in a.evidence_segment_ids)
            cells = [_cell(a.task), _cell(a.owner_display), _cell(a.deadline_display),
                     f'{ids}: "{_cell(a.evidence_quote)}"']
            lines.append(f"| {n} | " + " | ".join(cells) + " |")
        lines.append("")
    else:
        lines += ["_No action items were assigned._", ""]

    if record.rejected_items:
        lines += ["## Withheld by validation", "",
                  "These generated items were not supported by the transcript and are not part of the record:", ""]
        for r in record.rejected_items:
            lines.append(f"- **{r.kind.value}**: {'; '.join(r.reasons)}")
        lines.append("")

    lines += [f"_Generated by {record.document_model} (prompt {record.prompt_version})._", ""]
    return "\n".join(lines)


def action_items_csv(record: MeetingRecord) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["task", "owner", "deadline", "evidence_segment_ids", "evidence_quote"])
    for a in record.action_items:
        writer.writerow([a.task, a.owner or UNSPECIFIED, a.deadline or UNSPECIFIED,
                         " ".join(map(str, a.evidence_segment_ids)), a.evidence_quote])
    return buf.getvalue()


def complete_record(raw: RawTranscript, refined: RefinedTranscript, record: MeetingRecord) -> dict:
    """Everything about one processed meeting, as plain JSON-ready data."""
    return {
        "models": {
            "speech_to_text": raw.stt_model,
            "transcript_refinement": refined.refine_model,
            "meeting_documentation": record.document_model,
        },
        "meeting_record": record.model_dump(mode="json"),
        "raw_transcript": raw.model_dump(mode="json"),
        "refined_transcript": refined.model_dump(mode="json"),
    }


def _json(data: object) -> bytes:
    return json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")


def build_exports(raw: RawTranscript, refined: RefinedTranscript, record: MeetingRecord) -> list[ExportFile]:
    """All downloadable files for one processed meeting."""
    md, js, txt = "text/markdown", "application/json", "text/plain"
    return [
        ExportFile("raw_transcript", "raw_transcript.txt", txt, transcript_text(raw.segments).encode()),
        ExportFile("refined_transcript", "refined_transcript.txt", txt, transcript_text(refined.segments).encode()),
        ExportFile("meeting_record_md", "meeting_record.md", md, record_markdown(record).encode()),
        ExportFile("decisions", "decisions.json", js,
                   _json([d.model_dump(mode="json") for d in record.decisions])),
        ExportFile("action_items", "action_items.json", js,
                   _json([a.model_dump(mode="json") for a in record.action_items])),
        ExportFile("action_items_csv", "action_items.csv", "text/csv", action_items_csv(record).encode()),
        ExportFile("meeting_record_json", "meeting_record.json", js, _json(complete_record(raw, refined, record))),
    ]
