"""Human-readable and machine-readable renderings of a processed meeting.

Everything is rendered from the same ``RawTranscript``, ``RefinedTranscript``
and ``MeetingRecord`` objects the UI displays, so the Markdown, CSV and JSON
outputs always carry the same decisions and action items. Owners and deadlines
that were not stated appear as "Not specified" in human-readable files and as
``null`` in JSON.
"""

from __future__ import annotations

import csv
import io
import json
from dataclasses import dataclass

from ..schemas import MeetingRecord, RawTranscript, RefinedTranscript, Segment
from . import documents

NOT_SPECIFIED = "Not specified"


@dataclass(frozen=True)
class ExportFile:
    key: str
    label: str
    filename: str
    mime: str
    data: bytes


def timestamp(seconds: float) -> str:
    total = int(seconds)
    return f"{total // 3600:02d}:{total % 3600 // 60:02d}:{total % 60:02d}"


def transcript_text(segments: list[Segment], title: str = "") -> str:
    lines = [title, ""] if title else []
    lines += [f"[{timestamp(s.start)} - {timestamp(s.end)}] (#{s.id}) {s.text.strip()}"
              for s in segments if s.text.strip()]
    return "\n".join(lines) + "\n"


def _cell(text: str) -> str:
    """Make text safe inside a Markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ")


class _Citer:
    """Formats evidence references with timestamps from the refined transcript."""

    def __init__(self, segments: list[Segment] | None) -> None:
        self.times = {s.id: s.start for s in segments or []}

    def ids(self, ids: list[int]) -> str:
        return ", ".join(f"#{i} @ {timestamp(self.times[i])}" if i in self.times else f"#{i}" for i in ids)

    def evidence(self, ids: list[int], quote: str) -> str:
        return f'_Evidence ({self.ids(ids)}): "{quote}"_'


def _summary_md(record: MeetingRecord) -> list[str]:
    return ["## Summary", "", record.summary or "_Summary withheld: it failed validation._", ""]


def _minutes_md(record: MeetingRecord, cite: _Citer) -> list[str]:
    lines = ["## Minutes", ""]
    if not record.minutes:
        return lines + ["_No minutes._", ""]
    for m in record.minutes:
        lines += [f"### {m.topic}", "", m.discussion, "", f"_Segments: {cite.ids(m.segment_ids)}_", ""]
    return lines


def _decisions_md(record: MeetingRecord, cite: _Citer) -> list[str]:
    lines = ["## Decisions", ""]
    if not record.decisions:
        return lines + ["_No decisions were recorded._", ""]
    for n, d in enumerate(record.decisions, 1):
        lines += [f"{n}. {d.decision}", f"   {cite.evidence(d.evidence_segment_ids, d.evidence_quote)}"]
    return lines + [""]


def _proposals_md(record: MeetingRecord, cite: _Citer) -> list[str]:
    lines = ["## Proposals (discussed, not agreed)", ""]
    if not record.proposals:
        return lines + ["_No open proposals._", ""]
    for n, p in enumerate(record.proposals, 1):
        lines += [f"{n}. {p.proposal}", f"   {cite.evidence(p.evidence_segment_ids, p.evidence_quote)}"]
    return lines + [""]


def _actions_md(record: MeetingRecord, cite: _Citer) -> list[str]:
    lines = ["## Action items", ""]
    if not record.action_items:
        return lines + ["_No action items were assigned._", ""]
    lines += ["| # | Task | Owner | Deadline | Evidence |", "|---|---|---|---|---|"]
    for n, a in enumerate(record.action_items, 1):
        cells = [_cell(a.task), _cell(a.owner or NOT_SPECIFIED), _cell(a.deadline or NOT_SPECIFIED),
                 f'{cite.ids(a.evidence_segment_ids)}: "{_cell(a.evidence_quote)}"']
        lines.append(f"| {n} | " + " | ".join(cells) + " |")
    return lines + [""]


def _withheld_md(record: MeetingRecord) -> list[str]:
    if not record.rejected_items:
        return []
    lines = ["## Withheld by validation", "",
             "These generated items were not supported by the transcript and are not part of the record:", ""]
    for r in record.rejected_items:
        lines.append(f"- **{r.kind.value}**: {'; '.join(r.reasons)}")
    return lines + [""]


def _footer(record: MeetingRecord) -> list[str]:
    return [f"_Generated by {record.document_model} (prompt {record.prompt_version})._", ""]


def record_markdown(record: MeetingRecord, segments: list[Segment] | None = None,
                    title: str = "Meeting record") -> str:
    cite = _Citer(segments)
    return "\n".join([f"# {title}", "", *_summary_md(record), *_minutes_md(record, cite),
                      *_decisions_md(record, cite), *_proposals_md(record, cite),
                      *_actions_md(record, cite), *_withheld_md(record), *_footer(record)])


def minutes_markdown(record: MeetingRecord, segments: list[Segment] | None = None) -> str:
    cite = _Citer(segments)
    return "\n".join(["# Meeting minutes", "", *_summary_md(record), *_minutes_md(record, cite),
                      *_footer(record)])


def decisions_markdown(record: MeetingRecord, segments: list[Segment] | None = None) -> str:
    cite = _Citer(segments)
    return "\n".join(["# Decisions and proposals", "", *_decisions_md(record, cite),
                      *_proposals_md(record, cite), *_footer(record)])


def action_items_csv(record: MeetingRecord) -> str:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["task", "owner", "deadline", "evidence_segment_ids", "evidence_quote"])
    for a in record.action_items:
        writer.writerow([a.task, a.owner or NOT_SPECIFIED, a.deadline or NOT_SPECIFIED,
                         " ".join(map(str, a.evidence_segment_ids)), a.evidence_quote])
    return buf.getvalue()


def complete_record(raw: RawTranscript | None, refined: RefinedTranscript | None,
                    record: MeetingRecord | None) -> dict:
    """Everything about one processed meeting, as plain JSON-ready data built
    from the existing Pydantic models (no separate data model)."""
    return {
        "models": {
            "speech_to_text": raw.stt_model if raw else None,
            "transcript_refinement": refined.refine_model if refined else None,
            "meeting_documentation": record.document_model if record else None,
        },
        "raw_transcript": raw.model_dump(mode="json") if raw else None,
        "refined_transcript": refined.model_dump(mode="json") if refined else None,
        "meeting_record": record.model_dump(mode="json") if record else None,
    }


def _json(data: object) -> bytes:
    return json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")


def build_exports(raw: RawTranscript | None, refined: RefinedTranscript | None,
                  record: MeetingRecord | None, source_name: str | None = None) -> list[ExportFile]:
    """All downloadable files available for one meeting (partial results allowed).

    Text/Markdown/CSV/JSON files come first, then a PDF and a Word version of
    each deliverable (raw transcript, refined transcript, minutes, key
    decisions, action items, complete record).
    """
    files = _data_exports(raw, refined, record)
    for doc in documents.build_documents(raw, refined, record, source_name):
        files.append(ExportFile(f"{doc.key}_pdf", f"{doc.title} (PDF)", f"{doc.filename_stem}.pdf",
                                documents.PDF_MIME, documents.render_pdf(doc)))
        files.append(ExportFile(f"{doc.key}_docx", f"{doc.title} (Word)", f"{doc.filename_stem}.docx",
                                documents.DOCX_MIME, documents.render_docx(doc)))
    return files


def _data_exports(raw: RawTranscript | None, refined: RefinedTranscript | None,
                  record: MeetingRecord | None) -> list[ExportFile]:
    md, js, txt = "text/markdown", "application/json", "text/plain"
    files: list[ExportFile] = []
    if raw:
        files.append(ExportFile("raw_transcript", "Raw transcript", "raw_transcript.txt", txt,
                                transcript_text(raw.segments, f"Raw transcript ({raw.stt_model})").encode()))
    if refined:
        files.append(ExportFile("refined_transcript", "Refined transcript", "refined_transcript.txt", txt,
                                transcript_text(refined.segments,
                                                f"Refined transcript ({refined.refine_model})").encode()))
    if record:
        segs = refined.segments if refined else None
        files += [
            ExportFile("minutes", "Meeting minutes", "meeting_minutes.md", md,
                       minutes_markdown(record, segs).encode()),
            ExportFile("decisions", "Decisions", "decisions.md", md, decisions_markdown(record, segs).encode()),
            ExportFile("decisions_json", "Decisions (JSON)", "decisions.json", js,
                       _json([d.model_dump(mode="json") for d in record.decisions])),
            ExportFile("action_items", "Action items (CSV)", "action_items.csv", "text/csv",
                       action_items_csv(record).encode()),
            ExportFile("action_items_json", "Action items (JSON)", "action_items.json", js,
                       _json([a.model_dump(mode="json") for a in record.action_items])),
            ExportFile("meeting_record_md", "Complete meeting record", "meeting_record.md", md,
                       record_markdown(record, segs).encode()),
        ]
    if raw or refined or record:
        files.append(ExportFile("meeting_record_json", "Complete meeting record (JSON)", "meeting_record.json",
                                js, _json(complete_record(raw, refined, record))))
    return files
